using Application.Interfaces;
using Application.Settings;
using LibGit2Sharp;
using System.Text.RegularExpressions;

namespace Application.Services;

public class GithubService(ApplicationSettings applicationSettings) : IGithubService
{
    private readonly string _githubToken = applicationSettings.GitHubToken;

    //Branch hardcoded to develop. Maybe make configurable later.
    public async Task PullLatestDevelopAsync(string repositoryPath)
    {
        await Task.Run(() =>
        {
            using var repo = new Repository(repositoryPath);

            // Checkout develop branch
            var developBranch = repo.Branches["develop"] ?? repo.Branches["origin/develop"];
            if (developBranch == null)
            {
                throw new InvalidOperationException("Develop branch not found");
            }

            // Checkout develop if not already on it
            if (repo.Head.FriendlyName != "develop")
            {
                Commands.Checkout(repo, developBranch);
            }

            // Pull latest changes.
            var signature = new Signature("AI Assistant", "ai@assistant.local", DateTimeOffset.Now);
            var pullOptions = new PullOptions
            {
                FetchOptions = new FetchOptions
                {
                    CredentialsProvider = (url, usernameFromUrl, types) =>
                        new UsernamePasswordCredentials
                        {
                            Username = _githubToken,
                            Password = string.Empty
                        }
                }
            };
            Commands.Pull(repo, signature, pullOptions);
        });
    }

    public async Task<string> CreateBranchAsync(string ticketTitle, string repositoryPath)
    {
        return await Task.Run(() =>
        {
            using var repo = new Repository(repositoryPath);

            // Sanitize ticket title for branch name
            var sanitizedTitle = SanitizeBranchName(ticketTitle);
            var timestamp = DateTime.Now.ToString("yyyyMMdd-HHmmss");
            var branchName = $"feature/auto-{sanitizedTitle}-{timestamp}";

            // Ensure we're on develop before creating branch
            var developBranch = repo.Branches["develop"];
            if (developBranch == null)
            {
                throw new InvalidOperationException("Develop branch not found");
            }

            // Create new branch from develop
            var newBranch = repo.CreateBranch(branchName, developBranch.Tip);
            Commands.Checkout(repo, newBranch);

            return branchName;
        });
    }

    public async Task CommitAndPushBranchAsync(string branchName, string title, string description, string repositoryPath)
    {
        await Task.Run(() =>
        {
            using var repo = new Repository(repositoryPath);

            var branch = repo.Branches[branchName];
            if (branch == null)
            {
                throw new InvalidOperationException($"Branch {branchName} not found");
            }

            // Check if there are any changes to stage
            var status = repo.RetrieveStatus();
            if (!status.IsDirty)
            {
                throw new InvalidOperationException("No changes to commit");
            }

            // Debug: Print what status sees
            Console.WriteLine($"Status counts - Modified: {status.Modified.Count()}, Added: {status.Added.Count()}, Removed: {status.Removed.Count()}, Untracked: {status.Untracked.Count()}");

            // Try using the status entries directly
            foreach (var entry in status)
            {
                Console.WriteLine($"Staging file: {entry.FilePath} - State: {entry.State}");
                Commands.Stage(repo, entry.FilePath);
            }

            // Create commit
            var signature = new Signature("AI Assistant", "ai@assistant.local", DateTimeOffset.Now);
            var commitMessage = $"{title}\n\n{description}\n\nGenerated by AI Assistant";
            repo.Commit(commitMessage, signature, signature);

            var remote = repo.Network.Remotes["origin"];
            var options = new PushOptions
            {
                CredentialsProvider = (url, usernameFromUrl, types) =>
                    new UsernamePasswordCredentials
                    {
                        Username = _githubToken,
                        Password = string.Empty
                    }
            };

            // Push with upstream tracking (equivalent to git push --set-upstream origin branchName)
            var pushRefSpec = $"+refs/heads/{branchName}:refs/heads/{branchName}";
            repo.Network.Push(remote, pushRefSpec, options);

            // Set the upstream tracking branch
            repo.Branches.Update(branch, b => b.TrackedBranch = $"refs/remotes/origin/{branchName}");
        });
    }

    private static string SanitizeBranchName(string input)
    {
        // Remove invalid characters and replace spaces with dashes
        var sanitized = Regex.Replace(input, @"[^a-zA-Z0-9\s-]", "");
        sanitized = Regex.Replace(sanitized, @"\s+", "-");
        sanitized = sanitized.Trim('-').ToLowerInvariant();

        // Limit length to avoid overly long branch names
        if (sanitized.Length > 50)
        {
            sanitized = sanitized.Substring(0, 50).TrimEnd('-');
        }

        return sanitized;
    }
}